package camera.vimal.vk;

import java.io.File;
import java.io.IOException;
import java.util.Date;
import java.util.List;
import android.content.Context;
import android.graphics.Canvas;
import android.location.Location;
import android.net.Uri;
import android.util.Pair;
import android.view.MotionEvent;


public interface ApplicationInterface {
	class NoFreeStorageException extends Exception {
		private static final long serialVersionUID = 6064542819837033805L;
	}
	class VideoMaxFileSize {
		public long max_filesize;
		public boolean auto_restart;
	}
    int VIDEOMETHOD_FILE = 0;
	int VIDEOMETHOD_SAF = 1;
	int VIDEOMETHOD_URI = 2;
    Context getContext();
	boolean useCamera2();
	Location getLocation();
	int createOutputVideoMethod();
	File createOutputVideoFile() throws IOException;
	Uri createOutputVideoSAF() throws IOException;
	Uri createOutputVideoUri();
    int getCameraIdPref();
	String getFlashPref();
	String getFocusPref(boolean is_video);
	boolean isVideoPref();
	String getSceneModePref();
	String getColorEffectPref();
	String getWhiteBalancePref();
	int getWhiteBalanceTemperaturePref();
	String getAntiBandingPref();
	String getISOPref();
	int getExposureCompensationPref();
	Pair<Integer, Integer> getCameraResolutionPref();
	int getImageQualityPref();
	boolean getFaceDetectionPref();
	String getVideoQualityPref();
	boolean getVideoStabilizationPref();
	boolean getForce4KPref();
	String getVideoBitratePref();
	String getVideoFPSPref();
    float getVideoCaptureRateFactor();
	boolean useVideoLogProfile();
	float getVideoLogProfileStrength();
	long getVideoMaxDurationPref();
	int getVideoRestartTimesPref();
	VideoMaxFileSize getVideoMaxFileSizePref() throws NoFreeStorageException;
	boolean getVideoFlashPref();
	boolean getVideoLowPowerCheckPref();
	String getPreviewSizePref();
	String getPreviewRotationPref();
	String getLockOrientationPref();
    boolean getTouchCapturePref();
    boolean getDoubleTapCapturePref();
	boolean getPausePreviewPref();
	boolean getShowToastsPref();
	boolean getShutterSoundPref();
	boolean getStartupFocusPref();
	long getTimerPref();
	String getRepeatPref();
	long getRepeatIntervalPref();
	boolean getGeotaggingPref();
	boolean getRequireLocationPref();
	boolean getRecordAudioPref();
	String getRecordAudioChannelsPref();
	String getRecordAudioSourcePref();
	int getZoomPref();
	double getCalibratedLevelAngle();
	boolean canTakeNewPhoto();
	long getExposureTimePref();
	float getFocusDistancePref();
	boolean isExpoBracketingPref();
    int getExpoBracketingNImagesPref();
    double getExpoBracketingStopsPref();
	boolean getOptimiseAEForDROPref();
	boolean isCameraBurstPref();
	int getBurstNImages();
	boolean getBurstForNoiseReduction();
	enum RawPref {RAWPREF_JPEG_ONLY, RAWPREF_JPEG_DNG}
	RawPref getRawPref();
	int getMaxRawImages();
	boolean useCamera2FakeFlash();
	boolean useCamera2FastBurst();
	boolean usePhotoVideoRecording();
	boolean isTestAlwaysFocus();
    void cameraSetup();
	void touchEvent(MotionEvent event);
	void startingVideo();
	void startedVideo();
	void stoppingVideo();
	void stoppedVideo(final int video_method, final Uri uri, final String filename);
	void onFailedStartPreview();
	void onCameraError();
	void onPhotoError();
	void onVideoInfo(int what, int extra);
	void onVideoError(int what, int extra);
	void onVideoRecordStartError(VideoProfile profile);
	void onVideoRecordStopError(VideoProfile profile);
	void onFailedReconnectError();
	void onFailedCreateVideoFileError();
	void hasPausedPreview(boolean paused);
	void cameraInOperation(boolean in_operation, boolean is_video);
	void turnFrontScreenFlashOn();
	void cameraClosed();
	void timerBeep(long remaining_time);
	void layoutUI();
	void multitouchZoom(int new_zoom);
	void setCameraIdPref(int cameraId);
	void setFlashPref(String flash_value);
	void setFocusPref(String focus_value, boolean is_video);
	void setVideoPref(boolean is_video);
	void setSceneModePref(String scene_mode);
	void clearSceneModePref();
	void setColorEffectPref(String color_effect);
	void clearColorEffectPref();
	void setWhiteBalancePref(String white_balance);
	void clearWhiteBalancePref();
	void setWhiteBalanceTemperaturePref(int white_balance_temperature);
	void setISOPref(String iso);
	void clearISOPref();
	void setExposureCompensationPref(int exposure);
	void clearExposureCompensationPref();
	void setCameraResolutionPref(int width, int height);
	void setVideoQualityPref(String video_quality);
	void setZoomPref(int zoom);
	void requestCameraPermission();
	void requestStoragePermission();
	void requestRecordAudioPermission();
	void setExposureTimePref(long exposure_time);
	void clearExposureTimePref();
	void setFocusDistancePref(float focus_distance);
    void onDrawPreview(Canvas canvas);
	boolean onPictureTaken(byte [] data, Date current_date);
	boolean onBurstPictureTaken(List<byte []> images, Date current_date);
	boolean onRawPictureTaken(RawImage raw_image, Date current_date);
	void onCaptureStarted();
	void onPictureCompleted();
	void onContinuousFocusMove(boolean start);
}
